# Generated by Django 3.1.4 on 2021-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='名前')),
                ('education', models.CharField(max_length=35, verbose_name='教育')),
                ('github', models.CharField(max_length=35, verbose_name='GitHub')),
                ('facebook', models.CharField(max_length=35, verbose_name='facebook')),
                ('blog', models.CharField(max_length=35, verbose_name='blog')),
                ('mail', models.CharField(max_length=35, verbose_name='mail')),
                ('mobile', models.CharField(max_length=35, verbose_name='携帯')),
            ],
        ),
    ]
